name: digi_rentals
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.0
  persistent_bottom_nav_bar: ^4.0.2
  google_fonts: ^2.3.1
  file_picker: ^4.4.0
  get: ^4.6.1
  flutter_svg: ^1.0.3
  cloud_firestore: ^3.1.8
  firebase_core: ^1.12.0
  provider: ^6.0.2
  firebase_auth: ^3.3.7
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.0.8
  loading_overlay: ^0.3.0
  badges: ^2.0.2
  chat_bubbles: ^1.2.0
  flutter_share: ^2.0.0
  google_maps_flutter: any
  booster:
    git: https://github.com/MuhammadAliKust/Booster/

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/Images/Account/arrowforward.svg
    - assets/Images/Account/invitefireinds.svg
    - assets/Images/Account/logout.svg
    - assets/Images/Account/mycard.svg
    - assets/Images/Account/mylist.svg
    - assets/Images/Account/notificationsettings.svg
    - assets/Images/Account/paymenthistory.svg
    - assets/Images/Account/postedproducts.svg
    - assets/Images/Account/settings.svg
    - assets/Images/Account/waniningdialog.svg
    - assets/Images/AuthScreensImages/addusericon.svg
    - assets/Images/AuthScreensImages/cameraicon.svg
    - assets/Images/AuthScreensImages/emailicon.svg
    - assets/Images/AuthScreensImages/locationicon.svg
    - assets/Images/AuthScreensImages/logogreen.svg
    - assets/Images/AuthScreensImages/otpicon.svg
    - assets/Images/AuthScreensImages/passwordicon.svg
    - assets/Images/AuthScreensImages/personicon.svg
    - assets/Images/AuthScreensImages/phonenumbericon.svg
    - assets/Images/ChatImages/audiocallingicon.svg
    - assets/Images/ChatImages/cameraicon.svg
    - assets/Images/ChatImages/chatnowicon.svg
    - assets/Images/ChatImages/sendicon.svg
    - assets/Images/ChatImages/videocallingicon.svg
    - assets/Images/HomeScreenImages/bannerhomepage.png
    - assets/Images/HomeScreenImages/filter.svg
    - assets/Images/HomeScreenImages/home.svg
    - assets/Images/HomeScreenImages/john.svg
    - assets/Images/HomeScreenImages/messageicon.svg
    - assets/Images/HomeScreenImages/noteicon.svg
    - assets/Images/HomeScreenImages/ourmotto.svg
    - assets/Images/HomeScreenImages/ourmottobac.svg
    - assets/Images/HomeScreenImages/personicon.svg
    - assets/Images/HomeScreenImages/search.svg
    - assets/Images/HomeScreenImages/searchicon.svg
    - assets/Images/HomeScreenImages/sucessimage.svg
    - assets/Images/HomeScreenImages/tickmark.svg
    - assets/Images/InviteFriends/arrowbackgreen.svg
    - assets/Images/InviteFriends/invitefriendbanner.svg
    - assets/Images/InviteFriends/sharingcodeicon.svg
    - assets/Images/MyCardImages/mastercardbac.svg
    - assets/Images/MyCardImages/visabac.svg
    - assets/Images/SearchScreenImages/carmechanices.svg
    - assets/Images/SearchScreenImages/carpetcare.svg
    - assets/Images/SearchScreenImages/carwash.svg
    - assets/Images/SearchScreenImages/constructionmanager.svg
    - assets/Images/SearchScreenImages/designers.svg
    - assets/Images/SearchScreenImages/electricall.svg
    - assets/Images/SearchScreenImages/garage.svg
    - assets/Images/SearchScreenImages/lawncare.svg
    - assets/Images/SearchScreenImages/movers.svg
    - assets/Images/SearchScreenImages/painters.svg
    - assets/Images/SearchScreenImages/plumbing.svg
    - assets/Images/SearchScreenImages/poolcare.svg
    - assets/Images/SearchScreenImages/roofers.svg
    - assets/Images/SearchScreenImages/woodwork.svg
    - assets/Images/SellerProfileImages/arrowbacks.svg
    - assets/Images/SellerProfileImages/detailsicon.svg
    - assets/Images/SellerProfileImages/hourclockicon.svg
    - assets/Images/SellerProfileImages/jobsdone.svg
    - assets/Images/SellerProfileImages/languages.svg
    - assets/Images/SellerProfileImages/warningsmall.svg
    - assets/Images/Services/carwash.svg
    - assets/Images/Services/cleaning.svg
    - assets/Images/Services/electrical.svg
    - assets/Images/Services/lawncare.svg
    - assets/Images/Services/plumbing.svg
    - assets/Images/SettingsImages/entermobilenicon.png
    - assets/Images/SettingsImages/faqsicon.svg
    - assets/Images/SettingsImages/helpcentericon.svg
    - assets/Images/SettingsImages/notificationicon.svg
    - assets/Images/SettingsImages/passwordicon.svg
    - assets/Images/SettingsImages/phoneicon.svg
    - assets/Images/SettingsImages/privacypolicyicon.svg
    - assets/Images/SettingsImages/termsandconditionicon.svg
    - assets/Images/SplashScreenImages/logowhite.svg
    - assets/Images/UploadProductImages/dotsbac.svg
    - assets/Images/UploadProductImages/uploadarrow.svg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
